// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PD_Helpers","status":true,"description":"0 - Some useful functions that are used by the system.","parameters":{}},
{"name":"PD_Global","status":true,"description":"1 - Takes care of the global save game where, for example, unlocked classes are stored.","parameters":{}},
{"name":"PD_UI","status":true,"description":"2 - Templates for some commonly used user interface elements.","parameters":{}},
{"name":"PD_Generator","status":true,"description":"3 - Generates dungeon levels during runtime.","parameters":{"defaultsHeader":"","defaultTileMappings":"[\"{\\\"DungeonId\\\":\\\"1\\\",\\\"RpgmId\\\":\\\"1\\\"}\",\"{\\\"DungeonId\\\":\\\"2\\\",\\\"RpgmId\\\":\\\"30\\\"}\",\"{\\\"DungeonId\\\":\\\"3\\\",\\\"RpgmId\\\":\\\"4\\\"}\",\"{\\\"DungeonId\\\":\\\"4\\\",\\\"RpgmId\\\":\\\"5\\\"}\",\"{\\\"DungeonId\\\":\\\"5\\\",\\\"RpgmId\\\":\\\"7\\\"}\",\"{\\\"DungeonId\\\":\\\"6\\\",\\\"RpgmId\\\":\\\"24\\\"}\"]","tilesetsHeader":"","perTilesetTileMappings":"[]"}},
{"name":"PD_FOW_FOV","status":true,"description":"4 - Implements the fog of war (FOW) and field of view (FOV) code the engine.","parameters":{"fowHeader":"","playerViewRange":"3","playerViewShape":"1","fogFadeSpeed":"0.1","fogOpacity":"1","fogDiscover":"true","fogDiscoveredOpacity":"0.5","fogShowEventsInDiscovered":"false","fogTileOcclusion":"[\"3\"]"}},
{"name":"PD_Pathfinding","status":true,"description":"5 - Allows characters to calculate movement routes without getting stuck.","parameters":{}},
{"name":"Window_PDTitle","status":true,"description":"The Title screen.","parameters":{}},
{"name":"Window_PDOptions","status":true,"description":"The Options screen.","parameters":{}},
{"name":"Window_PDHero","status":true,"description":"The Choose Heo screen.","parameters":{}},
{"name":"Window_PDCredits","status":true,"description":"The Credits screen.","parameters":{}},
{"name":"Window_PDBadges","status":true,"description":"The Badges screen.","parameters":{}},
{"name":"Window_PDUI","status":true,"description":"The panels that are shown over the game map while playing.","parameters":{}}
];
