// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"======CORE==============================================","status":false,"description":"","parameters":{}},
{"name":"PD_Helpers","status":true,"description":"C1 - Some useful functions that are used by the system.","parameters":{}},
{"name":"PD_Global","status":true,"description":"C2 - Takes care of the global save game where, for example, unlocked classes are stored.","parameters":{}},
{"name":"PD_Tiles","status":true,"description":"C3 - An index of all available mapping tiles in the system.","parameters":{}},
{"name":"PD_Level","status":true,"description":"C4 - Base class for levels. Each level represents a dungeon depth.","parameters":{}},
{"name":"PD_Dungeon","status":true,"description":"C5 - Manages the game","parameters":{}},
{"name":"PD_UI","status":true,"description":"C6 - Templates for some commonly used user interface elements.","parameters":{}},
{"name":"PD_FOW_FOV","status":false,"description":"C7 - Implements the fog of war (FOW) and field of view (FOV) code the engine.","parameters":{"fowHeader":"","playerViewRange":"3","playerViewShape":"1","fogFadeSpeed":"0.1","fogOpacity":"1","fogDiscover":"true","fogDiscoveredOpacity":"0.5","fogShowEventsInDiscovered":"false","fogTileOcclusion":"[\"3\"]"}},
{"name":"PD_Pathfinding","status":true,"description":"C8 - Allows characters to calculate movement routes without getting stuck.","parameters":{}},
{"name":"======GENERATOR==========================================","status":false,"description":"","parameters":{}},
{"name":"PD_Generator","status":true,"description":"G1 - Generates dungeon levels during runtime.","parameters":{"defaultsHeader":"","defaultTileMappings":"[\"{\\\"DungeonId\\\":\\\"1\\\",\\\"RpgmId\\\":\\\"1\\\"}\",\"{\\\"DungeonId\\\":\\\"2\\\",\\\"RpgmId\\\":\\\"30\\\"}\",\"{\\\"DungeonId\\\":\\\"3\\\",\\\"RpgmId\\\":\\\"4\\\"}\",\"{\\\"DungeonId\\\":\\\"4\\\",\\\"RpgmId\\\":\\\"5\\\"}\",\"{\\\"DungeonId\\\":\\\"5\\\",\\\"RpgmId\\\":\\\"7\\\"}\",\"{\\\"DungeonId\\\":\\\"6\\\",\\\"RpgmId\\\":\\\"24\\\"}\"]","tilesetsHeader":"","perTilesetTileMappings":"[]"}},
{"name":"PD_GeneratorRect","status":true,"description":"G2 - Classes representing rectangles and points required by the generator","parameters":{}},
{"name":"PD_GeneratorRoom","status":true,"description":"G3 - Class that represents the rooms the generator creates","parameters":{}},
{"name":"PD_GeneratorPainter","status":true,"description":"G4 - Base class for other painters. It takes care of painting each room depending on the room type.","parameters":{}},
{"name":"======PAINTERS============================================","status":false,"description":"","parameters":{}},
{"name":"PD_Painter_Entrance","status":true,"description":"","parameters":{}},
{"name":"PD_Painter_Exit","status":true,"description":"","parameters":{}},
{"name":"PD_Painter_Simple","status":true,"description":"","parameters":{}},
{"name":"PD_Painter_NewTunnel","status":true,"description":"","parameters":{}},
{"name":"PD_Painter_Tunnel","status":true,"description":"","parameters":{}},
{"name":"======UI=================================================","status":false,"description":"","parameters":{}},
{"name":"Window_PDTitle","status":true,"description":"The Title screen.","parameters":{}},
{"name":"Window_PDOptions","status":true,"description":"The Options screen.","parameters":{}},
{"name":"Window_PDHero","status":true,"description":"The Choose Hero screen.","parameters":{}},
{"name":"Window_PDCredits","status":true,"description":"The Credits screen.","parameters":{}},
{"name":"Window_PDBadges","status":true,"description":"The Badges screen.","parameters":{}},
{"name":"Window_PDUI","status":true,"description":"The panels that are shown over the game map while playing.","parameters":{}}
];
